### ISSUE TITLE
Crash when resizing window

### ISSUE THREAD

**Issue by nyanpasu64** [chiptunecafe/rawrscope#16]
Git: master b3316d7e46509a0649cc6d131a259b7bbe0f0793
OS: Windows 10 x64

When I try to resize the window, I get panic messages from several threads:

```
PS C:\Users\nyanpasu\src\rawrscope> .\target\debug\rawrscope.exe
  WARN@wgpu_core::instance  Missing features: VERTEX_STORES_AND_ATOMICS | FRAGMENT_STORES_AND_ATOMICS
  WARN@wgpu_core::instance  max_bind_groups limit is missing
  WARN@wgpu_core::device  Surface does not support present mode: IMMEDIATE, falling back to FIFO
thread 'main' panicked at 'redraw event in non-redraw phase', <::std::macros::panic macros>:2:4
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libcore\fmt\mod.rs:1063
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:224
   9: alloc::boxed::{{impl}}::call
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\liballoc\boxed.rs:1031
  10: rawrscope::panic::dialog::{{closure}}
             at .\src\panic.rs:9
  11: std::panicking::rust_panic_with_hook
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:474
  12: std::panicking::begin_panic<str*>
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\panicking.rs:397
  13: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at <::std::macros::panic macros>:2
  14: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:161
  15: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:150
  16: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:104
  17: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:680
  18: DefSubclassProc
  19: DefSubclassProc
  20: CallWindowProcW
  21: DispatchMessageW
  22: IsWindowVisible
  23: KiUserCallbackDispatcher
  24: NtUserMessageCall
  25: GetWindowTextW
  26: MapWindowPoints
  27: IsCompositionActive
  28: Ordinal96
  29: IsCompositionActive
  30: IsCompositionActive
  31: GetWindowTextW
  32: DefSubclassProc
  33: DefSubclassProc
  34: CallWindowProcW
  35: DispatchMessageW
  36: IsWindowVisible
  37: KiUserCallbackDispatcher
  38: NtUserMessageCall
  39: GetWindowTextW
  40: MapWindowPoints
  41: IsCompositionActive
  42: Ordinal96
  43: IsCompositionActive
  44: IsCompositionActive
  45: GetWindowTextW
  46: CallWindowProcW
  47: CallWindowProcW
  48: DefSubclassProc
  49: DefSubclassProc
  50: DefSubclassProc
  51: DefSubclassProc
  52: CallWindowProcW
  53: DispatchMessageW
  54: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:235
  55: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:192
  56: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\event_loop.rs:148
  57: rawrscope::commands::app::_run
             at .\src\commands\app.rs:196
  58: rawrscope::commands::app::run
             at .\src\commands\app.rs:466
  59: rawrscope::main
             at .\src\main.rs:38
  60: std::rt::lang_start::{{closure}}<()>
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\rt.rs:67
  61: std::rt::lang_start_internal::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\rt.rs:52
  62: std::panicking::try::do_call<closure-0,i32>
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:303
  63: panic_unwind::__rust_maybe_catch_panic
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libpanic_unwind\lib.rs:86
  64: std::panicking::try
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:281
  65: std::panic::catch_unwind
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panic.rs:394
  66: std::rt::lang_start_internal
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\rt.rs:51
  67: main
  68: invoke_main
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  69: __scrt_common_main_seh
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  70: BaseThreadInitThunk
  71: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'already mutably borrowed: BorrowError', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore\cell.rs:798:9
stack backtrace:
   0:     0x7ff60ab374bf - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1:     0x7ff60ab374bf - std::sys_common::backtrace::_print_fmt
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff60ab374bf - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff60ab4eadb - core::fmt::write
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libcore\fmt\mod.rs:1063
   4:     0x7ff60ab33c1c - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\io\mod.rs:1426
   5:     0x7ff60ab3ab2c - std::sys_common::backtrace::_print
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff60ab3ab2c - std::sys_common::backtrace::print
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff60ab3ab2c - std::panicking::default_hook::{{closure}}
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:204
   8:     0x7ff60ab3a77f - std::panicking::default_hook
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:224
   9:     0x7ff60a7eb91a - alloc::boxed::{{impl}}::call
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\liballoc\boxed.rs:1031
  10:     0x7ff60a7eb91a - rawrscope::panic::dialog::{{closure}}
                               at C:\Users\nyanpasu\src\rawrscope\src\panic.rs:9
  11:     0x7ff60ab3b338 - std::panicking::rust_panic_with_hook
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:474
  12:     0x7ff60ab3ae8f - std::panicking::begin_panic_handler
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:378
  13:     0x7ff60ab4c750 - core::panicking::panic_fmt
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libcore\panicking.rs:85
  14:     0x7ff60ab4c593 - core::option::expect_none_failed
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libcore\option.rs:1211
  15:     0x7ff60a81983e - core::result::Result<core::cell::Ref<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>, core::cell::BorrowError>::expect
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore\result.rs:961
  16:     0x7ff60a81983e - core::cell::RefCell<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>::borrow
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore\cell.rs:798
  17:     0x7ff60a81983e - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:133
  18:     0x7ff60a7bdae0 - winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:104
  19:     0x7ff60a7bdae0 - winit::platform_impl::platform::event_loop::public_window_callback<()>
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:1367
  20:     0x7ff873a8b762 - DefSubclassProc
  21:     0x7ff873a8b625 - DefSubclassProc
  22:     0x7ff888955c0d - CallWindowProcW
  23:     0x7ff8889557dc - DispatchMessageW
  24:     0x7ff888961f73 - IsWindowVisible
  25:     0x7ff8894bfde4 - KiUserCallbackDispatcher
  26:     0x7ff886e38024 - NtUserCallHwndParamLockSafe
  27:     0x7ff88896bc77 - DialogBoxIndirectParamAorW
  28:     0x7ff8889b2f99 - SoftModalMessageBox
  29:     0x7ff8889b19d5 - DrawStateA
  30:     0x7ff8889b2712 - MessageBoxTimeoutW
  31:     0x7ff8889b279e - MessageBoxW
  32:     0x7ff60ac24654 - tinyfd_messageBoxW
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\libtinyfiledialogs\tinyfiledialogs.c:981
  33:     0x7ff60ac24654 - messageBoxWinGui8
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\libtinyfiledialogs\tinyfiledialogs.c:1015
  34:     0x7ff60ac2646b - tinyfd_messageBox
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\libtinyfiledialogs\tinyfiledialogs.c:2815
  35:     0x7ff60aa8949e - tinyfiledialogs::message_box
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\src\lib.rs:60
  36:     0x7ff60aa89851 - tinyfiledialogs::message_box_ok
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\tinyfiledialogs-3.3.9\src\lib.rs:88
  37:     0x7ff60a7eba1d - rawrscope::panic::dialog::{{closure}}
                               at C:\Users\nyanpasu\src\rawrscope\src\panic.rs:22
  38:     0x7ff60ab3b338 - std::panicking::rust_panic_with_hook
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:474
  39:     0x7ff60a80ef8d - std::panicking::begin_panic<str*>
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\panicking.rs:397
  40:     0x7ff60a81cc21 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
                               at <::std::macros::panic macros>:2
  41:     0x7ff60a8195e7 - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:161
  42:     0x7ff60a8195e7 - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop\runner.rs:150
  43:     0x7ff60a7be1f5 - winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:104
  44:     0x7ff60a7be1f5 - winit::platform_impl::platform::event_loop::public_window_callback<()>
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:680
  45:     0x7ff873a8b762 - DefSubclassProc
  46:     0x7ff873a8b625 - DefSubclassProc
  47:     0x7ff888955c0d - CallWindowProcW
  48:     0x7ff8889557dc - DispatchMessageW
  49:     0x7ff888961f73 - IsWindowVisible
  50:     0x7ff8894bfde4 - KiUserCallbackDispatcher
  51:     0x7ff886e31184 - NtUserMessageCall
  52:     0x7ff88895436a - GetWindowTextW
  53:     0x7ff888953aff - MapWindowPoints
  54:     0x7ff8840d984e - IsCompositionActive
  55:     0x7ff8840f25f2 - Ordinal96
  56:     0x7ff8840dc50f - IsCompositionActive
  57:     0x7ff8840dbff1 - IsCompositionActive
  58:     0x7ff88895403f - GetWindowTextW
  59:     0x7ff873a8b762 - DefSubclassProc
  60:     0x7ff873a8b625 - DefSubclassProc
  61:     0x7ff888955c0d - CallWindowProcW
  62:     0x7ff8889557dc - DispatchMessageW
  63:     0x7ff888961f73 - IsWindowVisible
  64:     0x7ff8894bfde4 - KiUserCallbackDispatcher
  65:     0x7ff886e31184 - NtUserMessageCall
  66:     0x7ff88895436a - GetWindowTextW
  67:     0x7ff888953aff - MapWindowPoints
  68:     0x7ff8840d984e - IsCompositionActive
  69:     0x7ff8840f2547 - Ordinal96
  70:     0x7ff8840dc50f - IsCompositionActive
  71:     0x7ff8840dbff1 - IsCompositionActive
  72:     0x7ff88895403f - GetWindowTextW
  73:     0x7ff888955c0d - CallWindowProcW
  74:     0x7ff8889558de - CallWindowProcW
  75:     0x7ff873a8b762 - DefSubclassProc
  76:     0x7ff873a8b51c - DefSubclassProc
  77:     0x7ff873a8b762 - DefSubclassProc
  78:     0x7ff873a8b625 - DefSubclassProc
  79:     0x7ff888955c0d - CallWindowProcW
  80:     0x7ff888955602 - DispatchMessageW
  81:     0x7ff60a7bcfcb - winit::platform_impl::platform::event_loop::EventLoop<()>::run_return
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:235
  82:     0x7ff60a7bcfcb - winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:192
  83:     0x7ff60a793962 - winit::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\nyanpasu\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\event_loop.rs:148
  84:     0x7ff60a7954f1 - rawrscope::commands::app::_run
                               at C:\Users\nyanpasu\src\rawrscope\src\commands\app.rs:196
  85:     0x7ff60a7954f1 - rawrscope::commands::app::run
                               at C:\Users\nyanpasu\src\rawrscope\src\commands\app.rs:466
  86:     0x7ff60a7c329d - rawrscope::main
                               at C:\Users\nyanpasu\src\rawrscope\src\main.rs:38
  87:     0x7ff60a7d5506 - std::rt::lang_start::{{closure}}<()>
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libstd\rt.rs:67
  88:     0x7ff60ab3ad27 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\rt.rs:52
  89:     0x7ff60ab3ad27 - std::panicking::try::do_call<closure-0,i32>
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:303
  90:     0x7ff60ab3eb42 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libpanic_unwind\lib.rs:86
  91:     0x7ff60ab3b648 - std::panicking::try
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panicking.rs:281
  92:     0x7ff60ab3b648 - std::panic::catch_unwind
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\panic.rs:394
  93:     0x7ff60ab3b648 - std::rt::lang_start_internal
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\/src\libstd\rt.rs:51
  94:     0x7ff60a7c3507 - main
  95:     0x7ff60ac27774 - invoke_main
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  96:     0x7ff60ac27774 - __scrt_common_main_seh
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  97:     0x7ff8886c7bd4 - BaseThreadInitThunk
  98:     0x7ff88948ce51 - RtlUserThreadStart
thread panicked while processing panic. aborting.
PS C:\Users\nyanpasu\src\rawrscope>
```

**Comment by rastertail** [comment]
Ah I recognize this one; it's a `winit` bug, already fixed upstream, but I have some other dependencies that require the older version. Will fix ASAP.
